module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "header-max-length": [2, "always", 100],
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "repo",
        "contracts",
        "config",
        "modules",
        "platform",
        "apps",
        "admin-app",
        "product-app",
        "public-web",
        "ops",
        "specs",
        "tests",
        "e2e",
        "security",
        "deps",
        "tooling",
        "docs",
        "ci",
      ],
    ],
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
  },
};
