/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SupportOperationsRouteImport } from './routes/support-operations'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RepairOperationsRouteImport } from './routes/repair-operations'
import { Route as RRouteImport } from './routes/r'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ComplianceRetentionRouteImport } from './routes/compliance-retention'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsIndexRouteImport } from './routes/tenants/index'
import { Route as DeskIndexRouteImport } from './routes/desk/index'
import { Route as RSplatRouteImport } from './routes/r/$'
import { Route as IntegrationsWebhooksApiAccessRouteImport } from './routes/integrations/webhooks-api-access'
import { Route as GovernanceRuntimeConfigRouteImport } from './routes/governance/runtime-config'
import { Route as GovernanceFeatureFlagsRouteImport } from './routes/governance/feature-flags'
import { Route as GovernanceAuditLogRouteImport } from './routes/governance/audit-log'
import { Route as GovernanceAccessControlRouteImport } from './routes/governance/access-control'
import { Route as DeskWebhookRouteImport } from './routes/desk/webhook'
import { Route as DeskVendorsRouteImport } from './routes/desk/vendors'
import { Route as DeskTenantsRouteImport } from './routes/desk/tenants'
import { Route as DeskSupportRouteImport } from './routes/desk/support'
import { Route as DeskSearchRouteImport } from './routes/desk/search'
import { Route as DeskRunsRouteImport } from './routes/desk/runs'
import { Route as DeskRetentionRouteImport } from './routes/desk/retention'
import { Route as DeskNotifyRouteImport } from './routes/desk/notify'
import { Route as DeskFlagRouteImport } from './routes/desk/flag'
import { Route as DeskConfigRouteImport } from './routes/desk/config'
import { Route as DeskBrandingRouteImport } from './routes/desk/branding'
import { Route as DeskBillingRouteImport } from './routes/desk/billing'
import { Route as DeskAuditRouteImport } from './routes/desk/audit'
import { Route as DeskAccessRouteImport } from './routes/desk/access'
import { Route as DeskSplatRouteImport } from './routes/desk/$'
import { Route as AuthStartRouteImport } from './routes/auth/start'
import { Route as AuthStaleSessionRouteImport } from './routes/auth/stale-session'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWorkspacesRouteImport } from './routes/admin/workspaces'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as DeskVendorServiceRouteImport } from './routes/desk/vendor/$service'
import { Route as DeskTenantTenantIdRouteImport } from './routes/desk/tenant/$tenantId'
import { Route as DeskRunIdRouteImport } from './routes/desk/run/$id'
import { Route as DeskOperatorIdRouteImport } from './routes/desk/operator/$id'
import { Route as DeskNotifyIdRouteImport } from './routes/desk/notify/$id'
import { Route as DeskMeterMeterIdRouteImport } from './routes/desk/meter/$meterId'
import { Route as DeskLegalHoldHoldIdRouteImport } from './routes/desk/legal-hold/$holdId'
import { Route as DeskKcUserIdRouteImport } from './routes/desk/kc-user/$id'
import { Route as DeskKcRoleIdRouteImport } from './routes/desk/kc-role/$id'
import { Route as DeskInvoiceInvoiceIdRouteImport } from './routes/desk/invoice/$invoiceId'
import { Route as DeskIncidentIncidentIdRouteImport } from './routes/desk/incident/$incidentId'
import { Route as DeskFlagFlagKeyRouteImport } from './routes/desk/flag/$flagKey'
import { Route as DeskDomainHostnameRouteImport } from './routes/desk/domain/$hostname'
import { Route as DeskDeliveryDeliveryIdRouteImport } from './routes/desk/delivery/$deliveryId'
import { Route as DeskApiKeyKeyIdRouteImport } from './routes/desk/api-key/$keyId'
import { Route as DeskAdminMemberIdRouteImport } from './routes/desk/admin-member/$id'
import { Route as DeskConfigModuleIdConfigKeyRouteImport } from './routes/desk/config/$moduleId/$configKey'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportOperationsRoute = SupportOperationsRouteImport.update({
  id: '/support-operations',
  path: '/support-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairOperationsRoute = RepairOperationsRouteImport.update({
  id: '/repair-operations',
  path: '/repair-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRetentionRoute = ComplianceRetentionRouteImport.update({
  id: '/compliance-retention',
  path: '/compliance-retention',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantsRoute,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const RSplatRoute = RSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RRoute,
} as any)
const IntegrationsWebhooksApiAccessRoute =
  IntegrationsWebhooksApiAccessRouteImport.update({
    id: '/integrations/webhooks-api-access',
    path: '/integrations/webhooks-api-access',
    getParentRoute: () => rootRouteImport,
  } as any)
const GovernanceRuntimeConfigRoute = GovernanceRuntimeConfigRouteImport.update({
  id: '/governance/runtime-config',
  path: '/governance/runtime-config',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceFeatureFlagsRoute = GovernanceFeatureFlagsRouteImport.update({
  id: '/governance/feature-flags',
  path: '/governance/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceAuditLogRoute = GovernanceAuditLogRouteImport.update({
  id: '/governance/audit-log',
  path: '/governance/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceAccessControlRoute = GovernanceAccessControlRouteImport.update({
  id: '/governance/access-control',
  path: '/governance/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskWebhookRoute = DeskWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => DeskRoute,
} as any)
const DeskVendorsRoute = DeskVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTenantsRoute = DeskTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSupportRoute = DeskSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSearchRoute = DeskSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DeskRoute,
} as any)
const DeskRunsRoute = DeskRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => DeskRoute,
} as any)
const DeskRetentionRoute = DeskRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => DeskRoute,
} as any)
const DeskNotifyRoute = DeskNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => DeskRoute,
} as any)
const DeskFlagRoute = DeskFlagRouteImport.update({
  id: '/flag',
  path: '/flag',
  getParentRoute: () => DeskRoute,
} as any)
const DeskConfigRoute = DeskConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBrandingRoute = DeskBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBillingRoute = DeskBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAuditRoute = DeskAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAccessRoute = DeskAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSplatRoute = DeskSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DeskRoute,
} as any)
const AuthStartRoute = AuthStartRouteImport.update({
  id: '/auth/start',
  path: '/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthStaleSessionRoute = AuthStaleSessionRouteImport.update({
  id: '/auth/stale-session',
  path: '/auth/stale-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/admin/workspaces',
  path: '/admin/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/admin/tokens',
  path: '/admin/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskVendorServiceRoute = DeskVendorServiceRouteImport.update({
  id: '/vendor/$service',
  path: '/vendor/$service',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTenantTenantIdRoute = DeskTenantTenantIdRouteImport.update({
  id: '/tenant/$tenantId',
  path: '/tenant/$tenantId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskRunIdRoute = DeskRunIdRouteImport.update({
  id: '/run/$id',
  path: '/run/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOperatorIdRoute = DeskOperatorIdRouteImport.update({
  id: '/operator/$id',
  path: '/operator/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskNotifyIdRoute = DeskNotifyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeskNotifyRoute,
} as any)
const DeskMeterMeterIdRoute = DeskMeterMeterIdRouteImport.update({
  id: '/meter/$meterId',
  path: '/meter/$meterId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLegalHoldHoldIdRoute = DeskLegalHoldHoldIdRouteImport.update({
  id: '/legal-hold/$holdId',
  path: '/legal-hold/$holdId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskKcUserIdRoute = DeskKcUserIdRouteImport.update({
  id: '/kc-user/$id',
  path: '/kc-user/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskKcRoleIdRoute = DeskKcRoleIdRouteImport.update({
  id: '/kc-role/$id',
  path: '/kc-role/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInvoiceInvoiceIdRoute = DeskInvoiceInvoiceIdRouteImport.update({
  id: '/invoice/$invoiceId',
  path: '/invoice/$invoiceId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskIncidentIncidentIdRoute = DeskIncidentIncidentIdRouteImport.update({
  id: '/incident/$incidentId',
  path: '/incident/$incidentId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskFlagFlagKeyRoute = DeskFlagFlagKeyRouteImport.update({
  id: '/$flagKey',
  path: '/$flagKey',
  getParentRoute: () => DeskFlagRoute,
} as any)
const DeskDomainHostnameRoute = DeskDomainHostnameRouteImport.update({
  id: '/domain/$hostname',
  path: '/domain/$hostname',
  getParentRoute: () => DeskRoute,
} as any)
const DeskDeliveryDeliveryIdRoute = DeskDeliveryDeliveryIdRouteImport.update({
  id: '/delivery/$deliveryId',
  path: '/delivery/$deliveryId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskApiKeyKeyIdRoute = DeskApiKeyKeyIdRouteImport.update({
  id: '/api-key/$keyId',
  path: '/api-key/$keyId',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAdminMemberIdRoute = DeskAdminMemberIdRouteImport.update({
  id: '/admin-member/$id',
  path: '/admin-member/$id',
  getParentRoute: () => DeskRoute,
} as any)
const DeskConfigModuleIdConfigKeyRoute =
  DeskConfigModuleIdConfigKeyRouteImport.update({
    id: '/$moduleId/$configKey',
    path: '/$moduleId/$configKey',
    getParentRoute: () => DeskConfigRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/branding': typeof BrandingRoute
  '/compliance-retention': typeof ComplianceRetentionRoute
  '/desk': typeof DeskRouteWithChildren
  '/profile': typeof ProfileRoute
  '/r': typeof RRouteWithChildren
  '/repair-operations': typeof RepairOperationsRoute
  '/sign-in': typeof SignInRoute
  '/support-operations': typeof SupportOperationsRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/stale-session': typeof AuthStaleSessionRoute
  '/auth/start': typeof AuthStartRoute
  '/desk/$': typeof DeskSplatRoute
  '/desk/access': typeof DeskAccessRoute
  '/desk/audit': typeof DeskAuditRoute
  '/desk/billing': typeof DeskBillingRoute
  '/desk/branding': typeof DeskBrandingRoute
  '/desk/config': typeof DeskConfigRouteWithChildren
  '/desk/flag': typeof DeskFlagRouteWithChildren
  '/desk/notify': typeof DeskNotifyRouteWithChildren
  '/desk/retention': typeof DeskRetentionRoute
  '/desk/runs': typeof DeskRunsRoute
  '/desk/search': typeof DeskSearchRoute
  '/desk/support': typeof DeskSupportRoute
  '/desk/tenants': typeof DeskTenantsRoute
  '/desk/vendors': typeof DeskVendorsRoute
  '/desk/webhook': typeof DeskWebhookRoute
  '/governance/access-control': typeof GovernanceAccessControlRoute
  '/governance/audit-log': typeof GovernanceAuditLogRoute
  '/governance/feature-flags': typeof GovernanceFeatureFlagsRoute
  '/governance/runtime-config': typeof GovernanceRuntimeConfigRoute
  '/integrations/webhooks-api-access': typeof IntegrationsWebhooksApiAccessRoute
  '/r/$': typeof RSplatRoute
  '/desk/': typeof DeskIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/desk/admin-member/$id': typeof DeskAdminMemberIdRoute
  '/desk/api-key/$keyId': typeof DeskApiKeyKeyIdRoute
  '/desk/delivery/$deliveryId': typeof DeskDeliveryDeliveryIdRoute
  '/desk/domain/$hostname': typeof DeskDomainHostnameRoute
  '/desk/flag/$flagKey': typeof DeskFlagFlagKeyRoute
  '/desk/incident/$incidentId': typeof DeskIncidentIncidentIdRoute
  '/desk/invoice/$invoiceId': typeof DeskInvoiceInvoiceIdRoute
  '/desk/kc-role/$id': typeof DeskKcRoleIdRoute
  '/desk/kc-user/$id': typeof DeskKcUserIdRoute
  '/desk/legal-hold/$holdId': typeof DeskLegalHoldHoldIdRoute
  '/desk/meter/$meterId': typeof DeskMeterMeterIdRoute
  '/desk/notify/$id': typeof DeskNotifyIdRoute
  '/desk/operator/$id': typeof DeskOperatorIdRoute
  '/desk/run/$id': typeof DeskRunIdRoute
  '/desk/tenant/$tenantId': typeof DeskTenantTenantIdRoute
  '/desk/vendor/$service': typeof DeskVendorServiceRoute
  '/desk/config/$moduleId/$configKey': typeof DeskConfigModuleIdConfigKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/branding': typeof BrandingRoute
  '/compliance-retention': typeof ComplianceRetentionRoute
  '/profile': typeof ProfileRoute
  '/r': typeof RRouteWithChildren
  '/repair-operations': typeof RepairOperationsRoute
  '/sign-in': typeof SignInRoute
  '/support-operations': typeof SupportOperationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/stale-session': typeof AuthStaleSessionRoute
  '/auth/start': typeof AuthStartRoute
  '/desk/$': typeof DeskSplatRoute
  '/desk/access': typeof DeskAccessRoute
  '/desk/audit': typeof DeskAuditRoute
  '/desk/billing': typeof DeskBillingRoute
  '/desk/branding': typeof DeskBrandingRoute
  '/desk/config': typeof DeskConfigRouteWithChildren
  '/desk/flag': typeof DeskFlagRouteWithChildren
  '/desk/notify': typeof DeskNotifyRouteWithChildren
  '/desk/retention': typeof DeskRetentionRoute
  '/desk/runs': typeof DeskRunsRoute
  '/desk/search': typeof DeskSearchRoute
  '/desk/support': typeof DeskSupportRoute
  '/desk/tenants': typeof DeskTenantsRoute
  '/desk/vendors': typeof DeskVendorsRoute
  '/desk/webhook': typeof DeskWebhookRoute
  '/governance/access-control': typeof GovernanceAccessControlRoute
  '/governance/audit-log': typeof GovernanceAuditLogRoute
  '/governance/feature-flags': typeof GovernanceFeatureFlagsRoute
  '/governance/runtime-config': typeof GovernanceRuntimeConfigRoute
  '/integrations/webhooks-api-access': typeof IntegrationsWebhooksApiAccessRoute
  '/r/$': typeof RSplatRoute
  '/desk': typeof DeskIndexRoute
  '/tenants': typeof TenantsIndexRoute
  '/desk/admin-member/$id': typeof DeskAdminMemberIdRoute
  '/desk/api-key/$keyId': typeof DeskApiKeyKeyIdRoute
  '/desk/delivery/$deliveryId': typeof DeskDeliveryDeliveryIdRoute
  '/desk/domain/$hostname': typeof DeskDomainHostnameRoute
  '/desk/flag/$flagKey': typeof DeskFlagFlagKeyRoute
  '/desk/incident/$incidentId': typeof DeskIncidentIncidentIdRoute
  '/desk/invoice/$invoiceId': typeof DeskInvoiceInvoiceIdRoute
  '/desk/kc-role/$id': typeof DeskKcRoleIdRoute
  '/desk/kc-user/$id': typeof DeskKcUserIdRoute
  '/desk/legal-hold/$holdId': typeof DeskLegalHoldHoldIdRoute
  '/desk/meter/$meterId': typeof DeskMeterMeterIdRoute
  '/desk/notify/$id': typeof DeskNotifyIdRoute
  '/desk/operator/$id': typeof DeskOperatorIdRoute
  '/desk/run/$id': typeof DeskRunIdRoute
  '/desk/tenant/$tenantId': typeof DeskTenantTenantIdRoute
  '/desk/vendor/$service': typeof DeskVendorServiceRoute
  '/desk/config/$moduleId/$configKey': typeof DeskConfigModuleIdConfigKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/branding': typeof BrandingRoute
  '/compliance-retention': typeof ComplianceRetentionRoute
  '/desk': typeof DeskRouteWithChildren
  '/profile': typeof ProfileRoute
  '/r': typeof RRouteWithChildren
  '/repair-operations': typeof RepairOperationsRoute
  '/sign-in': typeof SignInRoute
  '/support-operations': typeof SupportOperationsRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/stale-session': typeof AuthStaleSessionRoute
  '/auth/start': typeof AuthStartRoute
  '/desk/$': typeof DeskSplatRoute
  '/desk/access': typeof DeskAccessRoute
  '/desk/audit': typeof DeskAuditRoute
  '/desk/billing': typeof DeskBillingRoute
  '/desk/branding': typeof DeskBrandingRoute
  '/desk/config': typeof DeskConfigRouteWithChildren
  '/desk/flag': typeof DeskFlagRouteWithChildren
  '/desk/notify': typeof DeskNotifyRouteWithChildren
  '/desk/retention': typeof DeskRetentionRoute
  '/desk/runs': typeof DeskRunsRoute
  '/desk/search': typeof DeskSearchRoute
  '/desk/support': typeof DeskSupportRoute
  '/desk/tenants': typeof DeskTenantsRoute
  '/desk/vendors': typeof DeskVendorsRoute
  '/desk/webhook': typeof DeskWebhookRoute
  '/governance/access-control': typeof GovernanceAccessControlRoute
  '/governance/audit-log': typeof GovernanceAuditLogRoute
  '/governance/feature-flags': typeof GovernanceFeatureFlagsRoute
  '/governance/runtime-config': typeof GovernanceRuntimeConfigRoute
  '/integrations/webhooks-api-access': typeof IntegrationsWebhooksApiAccessRoute
  '/r/$': typeof RSplatRoute
  '/desk/': typeof DeskIndexRoute
  '/tenants/': typeof TenantsIndexRoute
  '/desk/admin-member/$id': typeof DeskAdminMemberIdRoute
  '/desk/api-key/$keyId': typeof DeskApiKeyKeyIdRoute
  '/desk/delivery/$deliveryId': typeof DeskDeliveryDeliveryIdRoute
  '/desk/domain/$hostname': typeof DeskDomainHostnameRoute
  '/desk/flag/$flagKey': typeof DeskFlagFlagKeyRoute
  '/desk/incident/$incidentId': typeof DeskIncidentIncidentIdRoute
  '/desk/invoice/$invoiceId': typeof DeskInvoiceInvoiceIdRoute
  '/desk/kc-role/$id': typeof DeskKcRoleIdRoute
  '/desk/kc-user/$id': typeof DeskKcUserIdRoute
  '/desk/legal-hold/$holdId': typeof DeskLegalHoldHoldIdRoute
  '/desk/meter/$meterId': typeof DeskMeterMeterIdRoute
  '/desk/notify/$id': typeof DeskNotifyIdRoute
  '/desk/operator/$id': typeof DeskOperatorIdRoute
  '/desk/run/$id': typeof DeskRunIdRoute
  '/desk/tenant/$tenantId': typeof DeskTenantTenantIdRoute
  '/desk/vendor/$service': typeof DeskVendorServiceRoute
  '/desk/config/$moduleId/$configKey': typeof DeskConfigModuleIdConfigKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/branding'
    | '/compliance-retention'
    | '/desk'
    | '/profile'
    | '/r'
    | '/repair-operations'
    | '/sign-in'
    | '/support-operations'
    | '/tenants'
    | '/admin/audit'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/tokens'
    | '/admin/workspaces'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/stale-session'
    | '/auth/start'
    | '/desk/$'
    | '/desk/access'
    | '/desk/audit'
    | '/desk/billing'
    | '/desk/branding'
    | '/desk/config'
    | '/desk/flag'
    | '/desk/notify'
    | '/desk/retention'
    | '/desk/runs'
    | '/desk/search'
    | '/desk/support'
    | '/desk/tenants'
    | '/desk/vendors'
    | '/desk/webhook'
    | '/governance/access-control'
    | '/governance/audit-log'
    | '/governance/feature-flags'
    | '/governance/runtime-config'
    | '/integrations/webhooks-api-access'
    | '/r/$'
    | '/desk/'
    | '/tenants/'
    | '/desk/admin-member/$id'
    | '/desk/api-key/$keyId'
    | '/desk/delivery/$deliveryId'
    | '/desk/domain/$hostname'
    | '/desk/flag/$flagKey'
    | '/desk/incident/$incidentId'
    | '/desk/invoice/$invoiceId'
    | '/desk/kc-role/$id'
    | '/desk/kc-user/$id'
    | '/desk/legal-hold/$holdId'
    | '/desk/meter/$meterId'
    | '/desk/notify/$id'
    | '/desk/operator/$id'
    | '/desk/run/$id'
    | '/desk/tenant/$tenantId'
    | '/desk/vendor/$service'
    | '/desk/config/$moduleId/$configKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/branding'
    | '/compliance-retention'
    | '/profile'
    | '/r'
    | '/repair-operations'
    | '/sign-in'
    | '/support-operations'
    | '/admin/audit'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/tokens'
    | '/admin/workspaces'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/stale-session'
    | '/auth/start'
    | '/desk/$'
    | '/desk/access'
    | '/desk/audit'
    | '/desk/billing'
    | '/desk/branding'
    | '/desk/config'
    | '/desk/flag'
    | '/desk/notify'
    | '/desk/retention'
    | '/desk/runs'
    | '/desk/search'
    | '/desk/support'
    | '/desk/tenants'
    | '/desk/vendors'
    | '/desk/webhook'
    | '/governance/access-control'
    | '/governance/audit-log'
    | '/governance/feature-flags'
    | '/governance/runtime-config'
    | '/integrations/webhooks-api-access'
    | '/r/$'
    | '/desk'
    | '/tenants'
    | '/desk/admin-member/$id'
    | '/desk/api-key/$keyId'
    | '/desk/delivery/$deliveryId'
    | '/desk/domain/$hostname'
    | '/desk/flag/$flagKey'
    | '/desk/incident/$incidentId'
    | '/desk/invoice/$invoiceId'
    | '/desk/kc-role/$id'
    | '/desk/kc-user/$id'
    | '/desk/legal-hold/$holdId'
    | '/desk/meter/$meterId'
    | '/desk/notify/$id'
    | '/desk/operator/$id'
    | '/desk/run/$id'
    | '/desk/tenant/$tenantId'
    | '/desk/vendor/$service'
    | '/desk/config/$moduleId/$configKey'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/branding'
    | '/compliance-retention'
    | '/desk'
    | '/profile'
    | '/r'
    | '/repair-operations'
    | '/sign-in'
    | '/support-operations'
    | '/tenants'
    | '/admin/audit'
    | '/admin/members'
    | '/admin/profile'
    | '/admin/tokens'
    | '/admin/workspaces'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/stale-session'
    | '/auth/start'
    | '/desk/$'
    | '/desk/access'
    | '/desk/audit'
    | '/desk/billing'
    | '/desk/branding'
    | '/desk/config'
    | '/desk/flag'
    | '/desk/notify'
    | '/desk/retention'
    | '/desk/runs'
    | '/desk/search'
    | '/desk/support'
    | '/desk/tenants'
    | '/desk/vendors'
    | '/desk/webhook'
    | '/governance/access-control'
    | '/governance/audit-log'
    | '/governance/feature-flags'
    | '/governance/runtime-config'
    | '/integrations/webhooks-api-access'
    | '/r/$'
    | '/desk/'
    | '/tenants/'
    | '/desk/admin-member/$id'
    | '/desk/api-key/$keyId'
    | '/desk/delivery/$deliveryId'
    | '/desk/domain/$hostname'
    | '/desk/flag/$flagKey'
    | '/desk/incident/$incidentId'
    | '/desk/invoice/$invoiceId'
    | '/desk/kc-role/$id'
    | '/desk/kc-user/$id'
    | '/desk/legal-hold/$holdId'
    | '/desk/meter/$meterId'
    | '/desk/notify/$id'
    | '/desk/operator/$id'
    | '/desk/run/$id'
    | '/desk/tenant/$tenantId'
    | '/desk/vendor/$service'
    | '/desk/config/$moduleId/$configKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  BrandingRoute: typeof BrandingRoute
  ComplianceRetentionRoute: typeof ComplianceRetentionRoute
  DeskRoute: typeof DeskRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RRoute: typeof RRouteWithChildren
  RepairOperationsRoute: typeof RepairOperationsRoute
  SignInRoute: typeof SignInRoute
  SupportOperationsRoute: typeof SupportOperationsRoute
  TenantsRoute: typeof TenantsRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthStaleSessionRoute: typeof AuthStaleSessionRoute
  AuthStartRoute: typeof AuthStartRoute
  GovernanceAccessControlRoute: typeof GovernanceAccessControlRoute
  GovernanceAuditLogRoute: typeof GovernanceAuditLogRoute
  GovernanceFeatureFlagsRoute: typeof GovernanceFeatureFlagsRoute
  GovernanceRuntimeConfigRoute: typeof GovernanceRuntimeConfigRoute
  IntegrationsWebhooksApiAccessRoute: typeof IntegrationsWebhooksApiAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-operations': {
      id: '/support-operations'
      path: '/support-operations'
      fullPath: '/support-operations'
      preLoaderRoute: typeof SupportOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-operations': {
      id: '/repair-operations'
      path: '/repair-operations'
      fullPath: '/repair-operations'
      preLoaderRoute: typeof RepairOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-retention': {
      id: '/compliance-retention'
      path: '/compliance-retention'
      fullPath: '/compliance-retention'
      preLoaderRoute: typeof ComplianceRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/r/$': {
      id: '/r/$'
      path: '/$'
      fullPath: '/r/$'
      preLoaderRoute: typeof RSplatRouteImport
      parentRoute: typeof RRoute
    }
    '/integrations/webhooks-api-access': {
      id: '/integrations/webhooks-api-access'
      path: '/integrations/webhooks-api-access'
      fullPath: '/integrations/webhooks-api-access'
      preLoaderRoute: typeof IntegrationsWebhooksApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/runtime-config': {
      id: '/governance/runtime-config'
      path: '/governance/runtime-config'
      fullPath: '/governance/runtime-config'
      preLoaderRoute: typeof GovernanceRuntimeConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/feature-flags': {
      id: '/governance/feature-flags'
      path: '/governance/feature-flags'
      fullPath: '/governance/feature-flags'
      preLoaderRoute: typeof GovernanceFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/audit-log': {
      id: '/governance/audit-log'
      path: '/governance/audit-log'
      fullPath: '/governance/audit-log'
      preLoaderRoute: typeof GovernanceAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/access-control': {
      id: '/governance/access-control'
      path: '/governance/access-control'
      fullPath: '/governance/access-control'
      preLoaderRoute: typeof GovernanceAccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/webhook': {
      id: '/desk/webhook'
      path: '/webhook'
      fullPath: '/desk/webhook'
      preLoaderRoute: typeof DeskWebhookRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/vendors': {
      id: '/desk/vendors'
      path: '/vendors'
      fullPath: '/desk/vendors'
      preLoaderRoute: typeof DeskVendorsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tenants': {
      id: '/desk/tenants'
      path: '/tenants'
      fullPath: '/desk/tenants'
      preLoaderRoute: typeof DeskTenantsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/support': {
      id: '/desk/support'
      path: '/support'
      fullPath: '/desk/support'
      preLoaderRoute: typeof DeskSupportRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/search': {
      id: '/desk/search'
      path: '/search'
      fullPath: '/desk/search'
      preLoaderRoute: typeof DeskSearchRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/runs': {
      id: '/desk/runs'
      path: '/runs'
      fullPath: '/desk/runs'
      preLoaderRoute: typeof DeskRunsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/retention': {
      id: '/desk/retention'
      path: '/retention'
      fullPath: '/desk/retention'
      preLoaderRoute: typeof DeskRetentionRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/notify': {
      id: '/desk/notify'
      path: '/notify'
      fullPath: '/desk/notify'
      preLoaderRoute: typeof DeskNotifyRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/flag': {
      id: '/desk/flag'
      path: '/flag'
      fullPath: '/desk/flag'
      preLoaderRoute: typeof DeskFlagRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/config': {
      id: '/desk/config'
      path: '/config'
      fullPath: '/desk/config'
      preLoaderRoute: typeof DeskConfigRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/branding': {
      id: '/desk/branding'
      path: '/branding'
      fullPath: '/desk/branding'
      preLoaderRoute: typeof DeskBrandingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/billing': {
      id: '/desk/billing'
      path: '/billing'
      fullPath: '/desk/billing'
      preLoaderRoute: typeof DeskBillingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/audit': {
      id: '/desk/audit'
      path: '/audit'
      fullPath: '/desk/audit'
      preLoaderRoute: typeof DeskAuditRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/access': {
      id: '/desk/access'
      path: '/access'
      fullPath: '/desk/access'
      preLoaderRoute: typeof DeskAccessRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/$': {
      id: '/desk/$'
      path: '/$'
      fullPath: '/desk/$'
      preLoaderRoute: typeof DeskSplatRouteImport
      parentRoute: typeof DeskRoute
    }
    '/auth/start': {
      id: '/auth/start'
      path: '/auth/start'
      fullPath: '/auth/start'
      preLoaderRoute: typeof AuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/stale-session': {
      id: '/auth/stale-session'
      path: '/auth/stale-session'
      fullPath: '/auth/stale-session'
      preLoaderRoute: typeof AuthStaleSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/vendor/$service': {
      id: '/desk/vendor/$service'
      path: '/vendor/$service'
      fullPath: '/desk/vendor/$service'
      preLoaderRoute: typeof DeskVendorServiceRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tenant/$tenantId': {
      id: '/desk/tenant/$tenantId'
      path: '/tenant/$tenantId'
      fullPath: '/desk/tenant/$tenantId'
      preLoaderRoute: typeof DeskTenantTenantIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/run/$id': {
      id: '/desk/run/$id'
      path: '/run/$id'
      fullPath: '/desk/run/$id'
      preLoaderRoute: typeof DeskRunIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/operator/$id': {
      id: '/desk/operator/$id'
      path: '/operator/$id'
      fullPath: '/desk/operator/$id'
      preLoaderRoute: typeof DeskOperatorIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/notify/$id': {
      id: '/desk/notify/$id'
      path: '/$id'
      fullPath: '/desk/notify/$id'
      preLoaderRoute: typeof DeskNotifyIdRouteImport
      parentRoute: typeof DeskNotifyRoute
    }
    '/desk/meter/$meterId': {
      id: '/desk/meter/$meterId'
      path: '/meter/$meterId'
      fullPath: '/desk/meter/$meterId'
      preLoaderRoute: typeof DeskMeterMeterIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/legal-hold/$holdId': {
      id: '/desk/legal-hold/$holdId'
      path: '/legal-hold/$holdId'
      fullPath: '/desk/legal-hold/$holdId'
      preLoaderRoute: typeof DeskLegalHoldHoldIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/kc-user/$id': {
      id: '/desk/kc-user/$id'
      path: '/kc-user/$id'
      fullPath: '/desk/kc-user/$id'
      preLoaderRoute: typeof DeskKcUserIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/kc-role/$id': {
      id: '/desk/kc-role/$id'
      path: '/kc-role/$id'
      fullPath: '/desk/kc-role/$id'
      preLoaderRoute: typeof DeskKcRoleIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/invoice/$invoiceId': {
      id: '/desk/invoice/$invoiceId'
      path: '/invoice/$invoiceId'
      fullPath: '/desk/invoice/$invoiceId'
      preLoaderRoute: typeof DeskInvoiceInvoiceIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/incident/$incidentId': {
      id: '/desk/incident/$incidentId'
      path: '/incident/$incidentId'
      fullPath: '/desk/incident/$incidentId'
      preLoaderRoute: typeof DeskIncidentIncidentIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/flag/$flagKey': {
      id: '/desk/flag/$flagKey'
      path: '/$flagKey'
      fullPath: '/desk/flag/$flagKey'
      preLoaderRoute: typeof DeskFlagFlagKeyRouteImport
      parentRoute: typeof DeskFlagRoute
    }
    '/desk/domain/$hostname': {
      id: '/desk/domain/$hostname'
      path: '/domain/$hostname'
      fullPath: '/desk/domain/$hostname'
      preLoaderRoute: typeof DeskDomainHostnameRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/delivery/$deliveryId': {
      id: '/desk/delivery/$deliveryId'
      path: '/delivery/$deliveryId'
      fullPath: '/desk/delivery/$deliveryId'
      preLoaderRoute: typeof DeskDeliveryDeliveryIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/api-key/$keyId': {
      id: '/desk/api-key/$keyId'
      path: '/api-key/$keyId'
      fullPath: '/desk/api-key/$keyId'
      preLoaderRoute: typeof DeskApiKeyKeyIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/admin-member/$id': {
      id: '/desk/admin-member/$id'
      path: '/admin-member/$id'
      fullPath: '/desk/admin-member/$id'
      preLoaderRoute: typeof DeskAdminMemberIdRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/config/$moduleId/$configKey': {
      id: '/desk/config/$moduleId/$configKey'
      path: '/$moduleId/$configKey'
      fullPath: '/desk/config/$moduleId/$configKey'
      preLoaderRoute: typeof DeskConfigModuleIdConfigKeyRouteImport
      parentRoute: typeof DeskConfigRoute
    }
  }
}

interface DeskConfigRouteChildren {
  DeskConfigModuleIdConfigKeyRoute: typeof DeskConfigModuleIdConfigKeyRoute
}

const DeskConfigRouteChildren: DeskConfigRouteChildren = {
  DeskConfigModuleIdConfigKeyRoute: DeskConfigModuleIdConfigKeyRoute,
}

const DeskConfigRouteWithChildren = DeskConfigRoute._addFileChildren(
  DeskConfigRouteChildren,
)

interface DeskFlagRouteChildren {
  DeskFlagFlagKeyRoute: typeof DeskFlagFlagKeyRoute
}

const DeskFlagRouteChildren: DeskFlagRouteChildren = {
  DeskFlagFlagKeyRoute: DeskFlagFlagKeyRoute,
}

const DeskFlagRouteWithChildren = DeskFlagRoute._addFileChildren(
  DeskFlagRouteChildren,
)

interface DeskNotifyRouteChildren {
  DeskNotifyIdRoute: typeof DeskNotifyIdRoute
}

const DeskNotifyRouteChildren: DeskNotifyRouteChildren = {
  DeskNotifyIdRoute: DeskNotifyIdRoute,
}

const DeskNotifyRouteWithChildren = DeskNotifyRoute._addFileChildren(
  DeskNotifyRouteChildren,
)

interface DeskRouteChildren {
  DeskSplatRoute: typeof DeskSplatRoute
  DeskAccessRoute: typeof DeskAccessRoute
  DeskAuditRoute: typeof DeskAuditRoute
  DeskBillingRoute: typeof DeskBillingRoute
  DeskBrandingRoute: typeof DeskBrandingRoute
  DeskConfigRoute: typeof DeskConfigRouteWithChildren
  DeskFlagRoute: typeof DeskFlagRouteWithChildren
  DeskNotifyRoute: typeof DeskNotifyRouteWithChildren
  DeskRetentionRoute: typeof DeskRetentionRoute
  DeskRunsRoute: typeof DeskRunsRoute
  DeskSearchRoute: typeof DeskSearchRoute
  DeskSupportRoute: typeof DeskSupportRoute
  DeskTenantsRoute: typeof DeskTenantsRoute
  DeskVendorsRoute: typeof DeskVendorsRoute
  DeskWebhookRoute: typeof DeskWebhookRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskAdminMemberIdRoute: typeof DeskAdminMemberIdRoute
  DeskApiKeyKeyIdRoute: typeof DeskApiKeyKeyIdRoute
  DeskDeliveryDeliveryIdRoute: typeof DeskDeliveryDeliveryIdRoute
  DeskDomainHostnameRoute: typeof DeskDomainHostnameRoute
  DeskIncidentIncidentIdRoute: typeof DeskIncidentIncidentIdRoute
  DeskInvoiceInvoiceIdRoute: typeof DeskInvoiceInvoiceIdRoute
  DeskKcRoleIdRoute: typeof DeskKcRoleIdRoute
  DeskKcUserIdRoute: typeof DeskKcUserIdRoute
  DeskLegalHoldHoldIdRoute: typeof DeskLegalHoldHoldIdRoute
  DeskMeterMeterIdRoute: typeof DeskMeterMeterIdRoute
  DeskOperatorIdRoute: typeof DeskOperatorIdRoute
  DeskRunIdRoute: typeof DeskRunIdRoute
  DeskTenantTenantIdRoute: typeof DeskTenantTenantIdRoute
  DeskVendorServiceRoute: typeof DeskVendorServiceRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskSplatRoute: DeskSplatRoute,
  DeskAccessRoute: DeskAccessRoute,
  DeskAuditRoute: DeskAuditRoute,
  DeskBillingRoute: DeskBillingRoute,
  DeskBrandingRoute: DeskBrandingRoute,
  DeskConfigRoute: DeskConfigRouteWithChildren,
  DeskFlagRoute: DeskFlagRouteWithChildren,
  DeskNotifyRoute: DeskNotifyRouteWithChildren,
  DeskRetentionRoute: DeskRetentionRoute,
  DeskRunsRoute: DeskRunsRoute,
  DeskSearchRoute: DeskSearchRoute,
  DeskSupportRoute: DeskSupportRoute,
  DeskTenantsRoute: DeskTenantsRoute,
  DeskVendorsRoute: DeskVendorsRoute,
  DeskWebhookRoute: DeskWebhookRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskAdminMemberIdRoute: DeskAdminMemberIdRoute,
  DeskApiKeyKeyIdRoute: DeskApiKeyKeyIdRoute,
  DeskDeliveryDeliveryIdRoute: DeskDeliveryDeliveryIdRoute,
  DeskDomainHostnameRoute: DeskDomainHostnameRoute,
  DeskIncidentIncidentIdRoute: DeskIncidentIncidentIdRoute,
  DeskInvoiceInvoiceIdRoute: DeskInvoiceInvoiceIdRoute,
  DeskKcRoleIdRoute: DeskKcRoleIdRoute,
  DeskKcUserIdRoute: DeskKcUserIdRoute,
  DeskLegalHoldHoldIdRoute: DeskLegalHoldHoldIdRoute,
  DeskMeterMeterIdRoute: DeskMeterMeterIdRoute,
  DeskOperatorIdRoute: DeskOperatorIdRoute,
  DeskRunIdRoute: DeskRunIdRoute,
  DeskTenantTenantIdRoute: DeskTenantTenantIdRoute,
  DeskVendorServiceRoute: DeskVendorServiceRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface RRouteChildren {
  RSplatRoute: typeof RSplatRoute
}

const RRouteChildren: RRouteChildren = {
  RSplatRoute: RSplatRoute,
}

const RRouteWithChildren = RRoute._addFileChildren(RRouteChildren)

interface TenantsRouteChildren {
  TenantsIndexRoute: typeof TenantsIndexRoute
}

const TenantsRouteChildren: TenantsRouteChildren = {
  TenantsIndexRoute: TenantsIndexRoute,
}

const TenantsRouteWithChildren =
  TenantsRoute._addFileChildren(TenantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  BrandingRoute: BrandingRoute,
  ComplianceRetentionRoute: ComplianceRetentionRoute,
  DeskRoute: DeskRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RRoute: RRouteWithChildren,
  RepairOperationsRoute: RepairOperationsRoute,
  SignInRoute: SignInRoute,
  SupportOperationsRoute: SupportOperationsRoute,
  TenantsRoute: TenantsRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthStaleSessionRoute: AuthStaleSessionRoute,
  AuthStartRoute: AuthStartRoute,
  GovernanceAccessControlRoute: GovernanceAccessControlRoute,
  GovernanceAuditLogRoute: GovernanceAuditLogRoute,
  GovernanceFeatureFlagsRoute: GovernanceFeatureFlagsRoute,
  GovernanceRuntimeConfigRoute: GovernanceRuntimeConfigRoute,
  IntegrationsWebhooksApiAccessRoute: IntegrationsWebhooksApiAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
