import { Schema } from "effect";

const PermissionScopeConstantSchema = Schema.Struct({
  tenantRead: Schema.Literal("tenant:read"),
  tenantWrite: Schema.Literal("tenant:write"),
  memberManage: Schema.Literal("member:manage"),
  configRead: Schema.Literal("config:read"),
  configWrite: Schema.Literal("config:write"),
  flagRead: Schema.Literal("flag:read"),
  flagWrite: Schema.Literal("flag:write"),
  fieldAdmin: Schema.Literal("field:admin"),
  fileRead: Schema.Literal("file:read"),
  fileWrite: Schema.Literal("file:write"),
  auditRead: Schema.Literal("audit:read"),
  brandingManage: Schema.Literal("branding:manage"),
  billingRead: Schema.Literal("billing:read"),
  billingWrite: Schema.Literal("billing:write"),
  observationRead: Schema.Literal("observation:read"),
  notificationManage: Schema.Literal("notification:manage"),
  webhookManage: Schema.Literal("webhook:manage"),
  searchAdmin: Schema.Literal("search:admin"),
  workflowManage: Schema.Literal("workflow:manage"),
  emailManage: Schema.Literal("email:manage"),
  importExecute: Schema.Literal("import:execute"),
  exportExecute: Schema.Literal("export:execute"),
  retentionManage: Schema.Literal("retention:manage"),
  supportImpersonate: Schema.Literal("support:impersonate"),
});

export const permissionScope = Schema.validateSync(
  PermissionScopeConstantSchema,
)({
  tenantRead: "tenant:read",
  tenantWrite: "tenant:write",
  memberManage: "member:manage",
  configRead: "config:read",
  configWrite: "config:write",
  flagRead: "flag:read",
  flagWrite: "flag:write",
  fieldAdmin: "field:admin",
  fileRead: "file:read",
  fileWrite: "file:write",
  auditRead: "audit:read",
  brandingManage: "branding:manage",
  billingRead: "billing:read",
  billingWrite: "billing:write",
  observationRead: "observation:read",
  notificationManage: "notification:manage",
  webhookManage: "webhook:manage",
  searchAdmin: "search:admin",
  workflowManage: "workflow:manage",
  emailManage: "email:manage",
  importExecute: "import:execute",
  exportExecute: "export:execute",
  retentionManage: "retention:manage",
  supportImpersonate: "support:impersonate",
} satisfies Schema.Schema.Type<typeof PermissionScopeConstantSchema>);

export const permissionScopes = [
  permissionScope.tenantRead,
  permissionScope.tenantWrite,
  permissionScope.memberManage,
  permissionScope.configRead,
  permissionScope.configWrite,
  permissionScope.flagRead,
  permissionScope.flagWrite,
  permissionScope.fieldAdmin,
  permissionScope.fileRead,
  permissionScope.fileWrite,
  permissionScope.auditRead,
  permissionScope.brandingManage,
  permissionScope.billingRead,
  permissionScope.billingWrite,
  permissionScope.observationRead,
  permissionScope.notificationManage,
  permissionScope.webhookManage,
  permissionScope.searchAdmin,
  permissionScope.workflowManage,
  permissionScope.emailManage,
  permissionScope.importExecute,
  permissionScope.exportExecute,
  permissionScope.retentionManage,
  permissionScope.supportImpersonate,
] as const;

export const PermissionScopeSchema = Schema.Literal(...permissionScopes);

export type PermissionScope = Schema.Schema.Type<typeof PermissionScopeSchema>;
