import { Schema } from "effect";

const PermissionScopeConstantSchema = Schema.Struct({
  tenantRead: Schema.Literal("tenant:read"),
  tenantWrite: Schema.Literal("tenant:write"),
  memberManage: Schema.Literal("member:manage"),
  configRead: Schema.Literal("config:read"),
  configWrite: Schema.Literal("config:write"),
  flagRead: Schema.Literal("flag:read"),
  flagWrite: Schema.Literal("flag:write"),
  fieldAdmin: Schema.Literal("field:admin"),
  fileRead: Schema.Literal("file:read"),
  fileWrite: Schema.Literal("file:write"),
  auditRead: Schema.Literal("audit:read"),
  brandingManage: Schema.Literal("branding:manage"),
  billingRead: Schema.Literal("billing:read"),
  billingWrite: Schema.Literal("billing:write"),
  observationRead: Schema.Literal("observation:read"),
  notificationManage: Schema.Literal("notification:manage"),
  webhookManage: Schema.Literal("webhook:manage"),
  searchAdmin: Schema.Literal("search:admin"),
  workflowManage: Schema.Literal("workflow:manage"),
  emailManage: Schema.Literal("email:manage"),
  importExecute: Schema.Literal("import:execute"),
  exportExecute: Schema.Literal("export:execute"),
  retentionManage: Schema.Literal("retention:manage"),
  supportImpersonate: Schema.Literal("support:impersonate"),
  adminOrganizationRead: Schema.Literal("admin-organization:read"),
  adminOrganizationInvite: Schema.Literal("admin-organization:invite"),
  adminOrganizationManageMembers: Schema.Literal(
    "admin-organization:manage-members",
  ),
  adminOrganizationChangeRole: Schema.Literal("admin-organization:change-role"),
  adminOrganizationRemoveMember: Schema.Literal(
    "admin-organization:remove-member",
  ),
  adminSavedViewsRead: Schema.Literal("admin-saved-views:read"),
  adminSavedViewsWrite: Schema.Literal("admin-saved-views:write"),
  adminSavedViewsDelete: Schema.Literal("admin-saved-views:delete"),
  adminWorkspacesRead: Schema.Literal("admin-workspaces:read"),
  adminWorkspacesWrite: Schema.Literal("admin-workspaces:write"),
  adminWorkspacesDelete: Schema.Literal("admin-workspaces:delete"),
  adminWorkspacesReorder: Schema.Literal("admin-workspaces:reorder"),
  operationsHomeRead: Schema.Literal("operations-home:read"),
  tenantWorkspaceRead: Schema.Literal("tenant-workspace:read"),
  manualBreakGlassIssue: Schema.Literal("manual-break-glass:issue"),
  manualBreakGlassRelease: Schema.Literal("manual-break-glass:release"),
  manualBreakGlassRead: Schema.Literal("manual-break-glass:read"),
  operatorWebhookDeliveryRead: Schema.Literal("operator-webhook-delivery:read"),
  operatorWebhookDeliveryReplay: Schema.Literal(
    "operator-webhook-delivery:replay",
  ),
  operatorWebhookDeliveryRetry: Schema.Literal(
    "operator-webhook-delivery:retry",
  ),
  operatorWebhookDeliveryCancel: Schema.Literal(
    "operator-webhook-delivery:cancel",
  ),
  polarRevenueProjectionRead: Schema.Literal("polar-revenue-projection:read"),
  polarRevenueProjectionBackfill: Schema.Literal(
    "polar-revenue-projection:backfill",
  ),
  openMeterUsageQueryRead: Schema.Literal("open-meter-usage-query:read"),
  openMeterUsageQueryBackfill: Schema.Literal(
    "open-meter-usage-query:backfill",
  ),
  vendorHealthAggregatorRead: Schema.Literal("vendor-health-aggregator:read"),
  keycloakRoleRead: Schema.Literal("keycloak-role-read:read"),
  keycloakUserRead: Schema.Literal("keycloak-user-read:read"),
  polarCustomerRead: Schema.Literal("polar-customer-read:read"),
  openMeterMeterRead: Schema.Literal("open-meter-meter-read:read"),
  novuDeliveriesRead: Schema.Literal("novu-deliveries-read:read"),
  postalMailLogRead: Schema.Literal("postal-mail-log-read:read"),
  glitchTipIssuesRead: Schema.Literal("glitchtip-issues-read:read"),
  openPanelEventsRead: Schema.Literal("openpanel-events-read:read"),
  universalSearchRead: Schema.Literal("universal-search:read"),
  capabilitySnapshotV2Read: Schema.Literal("capability-snapshot-v2:read"),
  runAsBannerStateRead: Schema.Literal("run-as-banner-state:read"),
  workflowRunsAdminRead: Schema.Literal("workflow-runs-admin:read"),
  workflowRunsAdminWrite: Schema.Literal("workflow-runs-admin:write"),
  notificationCenterAdminRead: Schema.Literal("notification-center-admin:read"),
  notificationCenterAdminWrite: Schema.Literal(
    "notification-center-admin:write",
  ),
  adminOperatorTestTokensManage: Schema.Literal(
    "admin-operator-test-tokens:manage",
  ),
});

export const permissionScope = Schema.validateSync(
  PermissionScopeConstantSchema,
)({
  tenantRead: "tenant:read",
  tenantWrite: "tenant:write",
  memberManage: "member:manage",
  configRead: "config:read",
  configWrite: "config:write",
  flagRead: "flag:read",
  flagWrite: "flag:write",
  fieldAdmin: "field:admin",
  fileRead: "file:read",
  fileWrite: "file:write",
  auditRead: "audit:read",
  brandingManage: "branding:manage",
  billingRead: "billing:read",
  billingWrite: "billing:write",
  observationRead: "observation:read",
  notificationManage: "notification:manage",
  webhookManage: "webhook:manage",
  searchAdmin: "search:admin",
  workflowManage: "workflow:manage",
  emailManage: "email:manage",
  importExecute: "import:execute",
  exportExecute: "export:execute",
  retentionManage: "retention:manage",
  supportImpersonate: "support:impersonate",
  adminOrganizationRead: "admin-organization:read",
  adminOrganizationInvite: "admin-organization:invite",
  adminOrganizationManageMembers: "admin-organization:manage-members",
  adminOrganizationChangeRole: "admin-organization:change-role",
  adminOrganizationRemoveMember: "admin-organization:remove-member",
  adminSavedViewsRead: "admin-saved-views:read",
  adminSavedViewsWrite: "admin-saved-views:write",
  adminSavedViewsDelete: "admin-saved-views:delete",
  adminWorkspacesRead: "admin-workspaces:read",
  adminWorkspacesWrite: "admin-workspaces:write",
  adminWorkspacesDelete: "admin-workspaces:delete",
  adminWorkspacesReorder: "admin-workspaces:reorder",
  operationsHomeRead: "operations-home:read",
  tenantWorkspaceRead: "tenant-workspace:read",
  manualBreakGlassIssue: "manual-break-glass:issue",
  manualBreakGlassRelease: "manual-break-glass:release",
  manualBreakGlassRead: "manual-break-glass:read",
  operatorWebhookDeliveryRead: "operator-webhook-delivery:read",
  operatorWebhookDeliveryReplay: "operator-webhook-delivery:replay",
  operatorWebhookDeliveryRetry: "operator-webhook-delivery:retry",
  operatorWebhookDeliveryCancel: "operator-webhook-delivery:cancel",
  polarRevenueProjectionRead: "polar-revenue-projection:read",
  polarRevenueProjectionBackfill: "polar-revenue-projection:backfill",
  openMeterUsageQueryRead: "open-meter-usage-query:read",
  openMeterUsageQueryBackfill: "open-meter-usage-query:backfill",
  vendorHealthAggregatorRead: "vendor-health-aggregator:read",
  keycloakRoleRead: "keycloak-role-read:read",
  keycloakUserRead: "keycloak-user-read:read",
  polarCustomerRead: "polar-customer-read:read",
  openMeterMeterRead: "open-meter-meter-read:read",
  novuDeliveriesRead: "novu-deliveries-read:read",
  postalMailLogRead: "postal-mail-log-read:read",
  glitchTipIssuesRead: "glitchtip-issues-read:read",
  openPanelEventsRead: "openpanel-events-read:read",
  universalSearchRead: "universal-search:read",
  capabilitySnapshotV2Read: "capability-snapshot-v2:read",
  runAsBannerStateRead: "run-as-banner-state:read",
  workflowRunsAdminRead: "workflow-runs-admin:read",
  workflowRunsAdminWrite: "workflow-runs-admin:write",
  notificationCenterAdminRead: "notification-center-admin:read",
  notificationCenterAdminWrite: "notification-center-admin:write",
  adminOperatorTestTokensManage: "admin-operator-test-tokens:manage",
} satisfies Schema.Schema.Type<typeof PermissionScopeConstantSchema>);

export const permissionScopes = [
  permissionScope.tenantRead,
  permissionScope.tenantWrite,
  permissionScope.memberManage,
  permissionScope.configRead,
  permissionScope.configWrite,
  permissionScope.flagRead,
  permissionScope.flagWrite,
  permissionScope.fieldAdmin,
  permissionScope.fileRead,
  permissionScope.fileWrite,
  permissionScope.auditRead,
  permissionScope.brandingManage,
  permissionScope.billingRead,
  permissionScope.billingWrite,
  permissionScope.observationRead,
  permissionScope.notificationManage,
  permissionScope.webhookManage,
  permissionScope.searchAdmin,
  permissionScope.workflowManage,
  permissionScope.emailManage,
  permissionScope.importExecute,
  permissionScope.exportExecute,
  permissionScope.retentionManage,
  permissionScope.supportImpersonate,
  permissionScope.adminOrganizationRead,
  permissionScope.adminOrganizationInvite,
  permissionScope.adminOrganizationManageMembers,
  permissionScope.adminOrganizationChangeRole,
  permissionScope.adminOrganizationRemoveMember,
  permissionScope.adminSavedViewsRead,
  permissionScope.adminSavedViewsWrite,
  permissionScope.adminSavedViewsDelete,
  permissionScope.adminWorkspacesRead,
  permissionScope.adminWorkspacesWrite,
  permissionScope.adminWorkspacesDelete,
  permissionScope.adminWorkspacesReorder,
  permissionScope.operationsHomeRead,
  permissionScope.tenantWorkspaceRead,
  permissionScope.manualBreakGlassIssue,
  permissionScope.manualBreakGlassRelease,
  permissionScope.manualBreakGlassRead,
  permissionScope.operatorWebhookDeliveryRead,
  permissionScope.operatorWebhookDeliveryReplay,
  permissionScope.operatorWebhookDeliveryRetry,
  permissionScope.operatorWebhookDeliveryCancel,
  permissionScope.polarRevenueProjectionRead,
  permissionScope.polarRevenueProjectionBackfill,
  permissionScope.openMeterUsageQueryRead,
  permissionScope.openMeterUsageQueryBackfill,
  permissionScope.vendorHealthAggregatorRead,
  permissionScope.keycloakRoleRead,
  permissionScope.keycloakUserRead,
  permissionScope.polarCustomerRead,
  permissionScope.openMeterMeterRead,
  permissionScope.novuDeliveriesRead,
  permissionScope.postalMailLogRead,
  permissionScope.glitchTipIssuesRead,
  permissionScope.openPanelEventsRead,
  permissionScope.universalSearchRead,
  permissionScope.capabilitySnapshotV2Read,
  permissionScope.runAsBannerStateRead,
  permissionScope.workflowRunsAdminRead,
  permissionScope.workflowRunsAdminWrite,
  permissionScope.notificationCenterAdminRead,
  permissionScope.notificationCenterAdminWrite,
  permissionScope.adminOperatorTestTokensManage,
] as const;

export const PermissionScopeSchema = Schema.Literal(...permissionScopes);

export type PermissionScope = Schema.Schema.Type<typeof PermissionScopeSchema>;
