services:
  unleash:
    container_name: unleash
    image: unleashorg/unleash-server:7.6.3
    environment:
      DATABASE_URL: ${UNLEASH_DATABASE_URL}
      DATABASE_SSL: "false"
      INIT_BACKEND_API_TOKENS: ${UNLEASH_API_TOKEN}
    depends_on:
      postgres-bootstrap:
        condition: service_completed_successfully
    ports:
      - 127.0.0.1:${UNLEASH_PORT:-4242}:4242
