services:
  ory-keto:
    container_name: ory-keto
    image: oryd/keto:v0.14.0
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "keto migrate up -y -c /etc/keto/keto.yml && exec keto serve -c /etc/keto/keto.yml",
      ]
    environment:
      DSN: ${KETO_DSN:-postgres://comvestec:comvestec@postgres:5432/keto?sslmode=disable}
    depends_on:
      vendor-postgres:
        condition: service_completed_successfully
    ports:
      - ${KETO_READ_PORT:-4466}:4466
      - ${KETO_WRITE_PORT:-4467}:4467
    volumes:
      - ./keto.yml:/etc/keto/keto.yml:ro
