services:
  ory-keto:
    container_name: ory-keto
    image: oryd/keto:v0.14.0
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "keto migrate up -y -c /etc/keto/keto.yml && exec keto serve -c /etc/keto/keto.yml",
      ]
    environment:
      DSN: ${KETO_DSN}
    depends_on:
      postgres-bootstrap:
        condition: service_completed_successfully
    ports:
      - 127.0.0.1:${KETO_READ_PORT:-4466}:4466
      - 127.0.0.1:${KETO_WRITE_PORT:-4467}:4467
    volumes:
      - ./keto.yml:/etc/keto/keto.yml:ro
