services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.41.0
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY:-meili-master-key}
      MEILI_ENV: ${MEILISEARCH_ENV:-development}
    ports:
      - ${MEILISEARCH_PORT:-7700}:7700
    volumes:
      - meilisearch_data:/meili_data

volumes:
  meilisearch_data:
